name: setup-go-test

on:
  workflow_dispatch:
  push:

jobs:
  go-action-test:
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: shahidhs-ibm/setup-go@ppc64le-support
        with:
          go-version: '1.21.1'
      - run: |
          go version
