name: setup-go-test

on:
  workflow_dispatch:
  push:

jobs:
  node-action-test:
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.13.7'
      - run: |
          go version
